### ISSUE TITLE
Clarify reporting components use

### ISSUE THREAD

**Issue by fabriziomoscon** [JaimeOverflow/VesselsDesign#2]
From your design, I understand that you recommend using QuickSight connected to the main RDS database, is that correct?
Please consider two factors:
- we would like to reduce to 0 the risk that analytical queries would impact the online transactional database
- we would like to guarantee that the analytics takes into considerations, data cleanup and enrichment that happens in spark jobs, in other words we don't want do have duplicate cleanup/normalisation jobs for data science and reporting.

I would appreciate a review design considering these 2 factors.

**Comment by JaimeOverflow** [comment]
I have updated the README explaining the changes related to this issue but let me summarise it.

To avoid impact into our postgres database, I will use the AWS Data Migration Service to transfer the data from our postgres database to our data warehouse database which is AWS Redshift. This online analytical database works very efficiently for analytical/aggregated queries because it has a columnar storage.

In terms of our AWS EMR, we can use Airflow to know when the spark jobs are done and the output data has been stored in the final S3 bucket so it can send a request to Redshift to ingest the S3 data into the data warehouse and it can be used to build dashboards in Quicksight. In this case we won't have duplicate cleanups/normalisation.
